name: Validate Butane

on: [push]

jobs:
  verify-json-validation:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'v1_4/testconfig.bu'
          schema: 'v1_4/butane-v1_4_0.json'
