name: Validate Changes

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'v*/*.json|*.json'
          
      - name: Validate butane v1.4 file using associate json schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'v1.4.0/testconfig.bu'
          schema: 'v1.4.0/butane-v1.4.0.json'
          
      - name: Validate butane v1.5 file using associate json schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'v1.5.0-experimental/testconfig.bu'
          schema: 'v1.5.0-experimental/butane-v1.5.0-experimental.json'
